### ISSUE TITLE
Error in Sys.setenv(TZ = tz) : wrong length for argument

### ISSUE THREAD

**Issue by fepsik** [grkhr/amocrm#1]
Выпадает вот такая вот ошибка при попытке получения чего-либо с помощью вашего пакета.
`Error in Sys.setenv(TZ = tz) : wrong length for argument`

**Comment by fepsik** [comment]
Проблема решилась тем что нашел свой api ключ. Вот тут вот инфа https://hamtim.ru/2020/07/02/%D0%BA%D0%B0%D0%BA-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C-api-%D0%BA%D0%BB%D1%8E%D1%87-amocrm/

**Comment by grkhr** [comment]
Спасибо за воркэраунд, добавлю в доку :)
